namespace CharacterEditor;

internal enum OptionB
{
	HDRARGB,
	SHOWMINI,
	SHOWPAWNLIST,
	SHOWTABS,
	STAYINCASCET,
	SHOWMAPVARS,
	SHOWINMENU,
	SHOWDEADLOGO,
	ZOMBOBJECTS,
	PAUSEGAME,
	MOREPAWNNAMES,
	CREATERACESPECIFIC,
	CREATENUDE,
	CREATENOWEAPON,
	CREATENOINV,
	USESORTEDPAWNLIST,
	DOAPPARELCHECK,
	USECHAOSABILITY,
	SHOWICONINSTARTING,
	SHOWBUTTONINSTARTING,
	SHOWBODYSIZEGENES,
	USEFIXEDSHADER,
	ADDCOMPCOLORABLE
}
